services:
  mongo:
    image: mongo:7.0.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: tibia-auction-history
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf