version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: tibia-auction-history
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
