export const getDefaultFilters = () => ({
  name: "",
  level: "",
  vocations: [],
  axeFighting: "",
  clubFighting: "",
  swordFighting: "",
  fistFighting: "",
  distanceFighting: "",
  magicLevel: "",
  shielding: "",
  fishing: "",
  items: [],
  storeItems: [],
  mounts: [],
  storeMounts: [],
  imbuements: [],
  completedQuestLines: [],
  titles: [],
  achievements: [],
  worlds: [],
  outfits: [],
  storeOutfits: [],
});
